const { Client, GatewayIntentBits, PermissionFlagsBits, SlashCommandBuilder, Routes } = require('discord.js');
const { REST } = require('@discordjs/rest');
const { createClient } = require('@supabase/supabase-js');
const express = require('express');

// --- 1. UptimeRobot & Render용 웹 서버 설정 ---
const app = express();
const PORT = process.env.PORT || 3000;

app.get('/', (req, res) => res.send('봇이 정상 작동 중입니다! (DB & 슬래시 커맨드 모드)'));
app.listen(PORT, () => console.log(`웹 서버가 ${PORT} 포트에서 준비되었습니다.`));

// --- 2. 외부 서비스 연결 (Supabase & Discord) ---
const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMembers, 
    GatewayIntentBits.GuildMessages, // 금지어 감지를 위해 추가
    GatewayIntentBits.MessageContent, // 금지어 감지를 위해 추가
  ],
});

// --- 3. 슬래시 명령어 등록 및 봇 준비 ---
client.on('ready', async () => {
  console.log(`${client.user.tag} 로그인이 완료되었습니다!`);

  const commands = [
    new SlashCommandBuilder()
      .setName('채널설정')
      .setDescription('환영 인사를 보낼 채널을 설정합니다. (관리자 전용)')
      .addChannelOption(option => 
        option.setName('채널')
          .setDescription('환영 인사를 보낼 채팅방을 선택해 주세요.')
          .setRequired(true))
      .setDefaultMemberPermissions(PermissionFlagsBits.Administrator) 
  ].map(command => command.toJSON());

  const rest = new REST({ version: '10' }).setToken(process.env.TOKEN);

  try {
    console.log('슬래시 명령어 등록을 시작합니다...');
    await rest.put(Routes.applicationCommands(client.user.id), { body: commands });
    console.log('슬래시 명령어 등록 완료!');
  } catch (error) {
    console.error('명령어 등록 중 에러 발생:', error);
  }
});

// --- 4. 슬래시 명령어 처리 (DB 저장) ---
client.on('interactionCreate', async (interaction) => {
  if (!interaction.isChatInputCommand()) return;

  if (interaction.commandName === '채널설정') {
    const channel = interaction.options.getChannel('채널');

    const { error } = await supabase
      .from('server_settings')
      .upsert({ 
        guild_id: interaction.guildId, 
        welcome_channel_id: channel.id 
      });

    if (error) {
      console.error('DB 저장 에러:', error);
      return interaction.reply({ content: '❌ 설정 저장 중 오류가 발생했습니다.', ephemeral: true });
    }

    await interaction.reply({
      content: `✅ 설정 완료! 앞으로 이 서버의 환영 인사는 ${channel} 채널에 전송됩니다.`,
      ephemeral: true 
    });
  }
});

// --- 5. 멤버 입장 시 환영 인사 전송 (DB 조회) ---
client.on('guildMemberAdd', async (member) => {
  if (member.user.bot) return;
  
  const { data, error } = await supabase
    .from('server_settings')
    .select('welcome_channel_id')
    .eq('guild_id', member.guild.id)
    .single();

  if (error || !data) {
    console.log('이 서버는 환영 채널 설정이 되어있지 않습니다.');
    return;
  }

  const channel = member.guild.channels.cache.get(data.welcome_channel_id);
  
  if (channel) {
    channel.send(`${member}님 오셔서 환영합니다!!

╰˚｡⋆📝<#1482351706628161649>에 양식에 맞춰서 자기소개 해주시고 나이성별 비공 가능합니다!

│˚｡⋆📢<#1476962498912714840>에 있는 │˚｡⋆📚<#1476961964419846176>이랑 │˚｡⋆⛔<#1497953540688187654> 확인 부탁드리겠습니다!

그리고 2일동안 자기소개 작성 안할 시 퇴장당하실 수 있습니다.`);
  }
});

// 봇 로그인
client.login(process.env.TOKEN);

// ==========================================
// 금지어 로직 (추가)
// ==========================================
const forbiddenWords = [
  "18년",
    "18놈",
    "18새끼",
    "ㄱㅐㅅㅐㄲl",
    "ㄱㅐㅈㅏ",
    "가슴만져",
    "가슴빨아",
    "가슴빨어",
    "가슴조물락",
    "가슴주물럭",
    "가슴쪼물딱",
    "가슴쪼물락",
    "가슴핧아",
    "가슴핧어",
    "강간",
    "개가튼년",
    "개가튼뇬",
    "개같은년",
    "개걸레",
    "개고치",
    "개너미",
    "개넘",
    "개년",
    "개놈",
    "개늠",
    "개똥",
    "개떵",
    "개떡",
    "개라슥",
    "개보지",
    "개부달",
    "개부랄",
    "개불랄",
    "개붕알",
    "개새",
    "개세",
    "개쓰래기",
    "개쓰레기",
    "개씁년",
    "개씁블",
    "개씁자지",
    "개씨발",
    "개씨블",
    "개자식",
    "개자지",
    "개잡년",
    "개젓가튼넘",
    "개좆",
    "개지랄",
    "개후라년",
    "개후라들놈",
    "개후라새끼",
    "걔잡년",
    "거시기",
    "걸래년",
    "걸레같은년",
    "걸레년",
    "걸레핀년",
    "게부럴",
    "게세끼",
    "게이",
    "게새끼",
    "게늠",
    "게자식",
    "게지랄놈",
    "고환",
    "귀두",
    "깨쌔끼",
    "난자마셔",
    "난자먹어",
    "난자핧아",
    "내꺼빨아",
    "내꺼핧아",
    "내버지",
    "내자지",
    "내잠지",
    "내조지",
    "너거애비",
    "노옴",
    "누나강간",
    "니기미",
    "니뿡",
    "니뽕",
    "니씨브랄",
    "니아범",
    "니아비",
    "니애미",
    "니애뷔",
    "니애비",
    "니할애비",
    "닝기미",
    "닌기미",
    "니미",
    "닳은년",
    "덜은새끼",
    "돈새끼",
    "돌으년",
    "돌은넘",
    "돌은새끼",
    "동생강간",
    "동성애자",
    "딸딸이",
    "똥구녁",
    "똥꾸뇽",
    "똥구뇽",
    "띠발뇬",
    "띠팔",
    "띠펄",
    "띠풀",
    "띠벌",
    "띠벨",
    "띠빌",
    "마스터",
    "막간년",
    "막대쑤셔줘",
    "막대핧아줘",
    "맛간년",
    "맛없는년",
    "맛이간년",
    "멜리스",
    "미친구녕",
    "미친구멍",
    "미친넘",
    "미친년",
    "미친놈",
    "미친눔",
    "미친새끼",
    "미친쇄리",
    "미친쇠리",
    "미친쉐이",
    "미친씨부랄",
    "미튄",
    "미티넘",
    "미틴",
    "미틴넘",
    "미틴년",
    "미틴놈",
    "미틴것",
    "백보지",
    "버따리자지",
    "버지구녕",
    "버지구멍",
    "버지냄새",
    "버지따먹기",
    "버지뚫어",
    "버지뜨더",
    "버지물마셔",
    "버지벌려",
    "버지벌료",
    "버지빨아",
    "버지빨어",
    "버지썰어",
    "버지쑤셔",
    "버지털",
    "버지핧아",
    "버짓물",
    "버짓물마셔",
    "벌창같은년",
    "벵신",
    "병닥",
    "병딱",
    "병신",
    "보쥐",
    "보지",
    "보지핧어",
    "보짓물",
    "보짓물마셔",
    "봉알",
    "부랄",
    "불알",
    "붕알",
    "붜지",
    "뷩딱",
    "븅쉰",
    "븅신",
    "빙띤",
    "빙신",
    "빠가십새",
    "빠가씹새",
    "빠구리",
    "빠굴이",
    "뻑큐",
    "뽕알",
    "뽀지",
    "뼝신",
    "사까시",
    "상년",
    "새꺄",
    "새뀌",
    "새끼",
    "색갸",
    "색끼",
    "색스",
    "색키",
    "샤발",
    "써글",
    "써글년",
    "성교",
    "성폭행",
    "세꺄",
    "세끼",
    "섹스",
    "섹스하자",
    "섹스해",
    "섹쓰",
    "섹히",
    "수셔",
    "쑤셔",
    "쉐끼",
    "쉑갸",
    "쉑쓰",
    "쉬발",
    "쉬방",
    "쉬밸년",
    "쉬벌",
    "쉬불",
    "쉬붕",
    "쉬빨",
    "쉬이발",
    "쉬이방",
    "쉬이벌",
    "쉬이불",
    "쉬이붕",
    "쉬이빨",
    "쉬이팔",
    "쉬이펄",
    "쉬이풀",
    "쉬팔",
    "쉬펄",
    "쉬풀",
    "쉽쌔",
    "시댕이",
    "시발",
    "시발년",
    "시발놈",
    "시발새끼",
    "시방새",
    "시밸",
    "시벌",
    "시불",
    "시붕",
    "시이발",
    "시이벌",
    "시이불",
    "시이붕",
    "시이팔",
    "시이펄",
    "시이풀",
    "시팍새끼",
    "시팔",
    "시팔넘",
    "시팔년",
    "시팔놈",
    "시팔새끼",
    "시펄",
    "실프",
    "십8",
    "십때끼",
    "십떼끼",
    "십버지",
    "십부랄",
    "십부럴",
    "십새",
    "십세이",
    "십셰리",
    "십쉐",
    "십자석",
    "십자슥",
    "십지랄",
    "십창녀",
    "십창",
    "십탱",
    "십탱구리",
    "십탱굴이",
    "느금마",
    "느금빠",
    "십팔새끼",
    "ㅆㅂ",
    "ㅆㅂㄹㅁ",
    "ㅆㅂㄻ",
    "ㅆㅣ",
    "쌍넘",
    "쌍년",
    "쌍놈",
    "쌍눔",
    "쌍보지",
    "쌔끼",
    "쌔리",
    "쌕스",
    "쌕쓰",
    "썅년",
    "썅놈",
    "썅뇬",
    "썅늠",
    "쓉새",
    "쓰바새끼",
    "쓰브랄쉽세",
    "씌발",
    "씌팔",
    "씨가랭넘",
    "씨가랭년",
    "씨가랭놈",
    "씨발",
    "씨발년",
    "씨발롬",
    "씨발병신",
    "씨방새",
    "씨방세",
    "씨밸",
    "씨뱅가리",
    "씨벌",
    "씨벌년",
    "씨벌쉐이",
    "씨부랄",
    "씨부럴",
    "씨불",
    "씨불알",
    "씨붕",
    "씨브럴",
    "씨블",
    "씨블년",
    "씨븡새끼",
    "씨빨",
    "씨이발",
    "씨이벌",
    "씨이불",
    "씨이붕",
    "씨이팔",
    "씨파넘",
    "씨팍새끼",
    "씨팍세끼",
    "씨팔",
    "씨펄",
    "씨퐁넘",
    "씨퐁뇬",
    "씨퐁보지",
    "씨퐁자지",
    "씹년",
    "씹물",
    "씹미랄",
    "씹버지",
    "씹보지",
    "씹부랄",
    "씹브랄",
    "씹빵구",
    "씹뽀지",
    "씹새",
    "씹새끼",
    "씹세",
    "씹쌔끼",
    "씹자석",
    "씹자슥",
    "씹자지",
    "씹지랄",
    "씹창",
    "씹창녀",
    "씹탱",
    "씹탱굴이",
    "씹탱이",
    "씹팔",
    "아가리",
    "애무",
    "애미",
    "애미랄",
    "애미보지",
    "애미씨뱅",
    "애미자지",
    "애미잡년",
    "애미좃물",
    "애비",
    "애자",
    "양아치",
    "어미강간",
    "어미따먹자",
    "어미쑤시자",
    "영자",
    "엄창",
    "에미",
    "에비",
    "엔플레버",
    "엠플레버",
    "염병",
    "염병할",
    "염뵹",
    "엿먹어라",
    "오랄",
    "오르가즘",
    "왕버지",
    "왕자지",
    "왕잠지",
    "왕털버지",
    "왕털보지",
    "왕털자지",
    "왕털잠지",
    "우미쑤셔",
    "운디네",
    "운영자",
    "유두",
    "유두빨어",
    "유두핧어",
    "유방",
    "유방만져",
    "유방빨아",
    "유방주물럭",
    "유방쪼물딱",
    "유방쪼물럭",
    "유방핧아",
    "유방핧어",
    "육갑",
    "이그니스",
    "이년",
    "이프리트",
    "자기핧아",
    "자지",
    "자지구녕",
    "자지구멍",
    "자지꽂아",
    "자지넣자",
    "자지뜨더",
    "자지뜯어",
    "자지박어",
    "자지빨아",
    "자지빨아줘",
    "자지빨어",
    "자지쑤셔",
    "자지쓰레기",
    "자지정개",
    "자지짤라",
    "자지털",
    "자지핧아",
    "자지핧아줘",
    "자지핧어",
    "작은보지",
    "잠지",
    "잠지뚫어",
    "잠지물마셔",
    "잠지털",
    "잠짓물마셔",
    "잡년",
    "잡놈",
    "저년",
    "점물",
    "젓가튼",
    "젓가튼쉐이",
    "젓같내",
    "젓같은",
    "젓까",
    "젓나",
    "젓냄새",
    "젓대가리",
    "젓떠",
    "젓마무리",
    "젓만이",
    "젓물",
    "젓물냄새",
    "젓밥",
    "정액마셔",
    "정액먹어",
    "정액발사",
    "정액짜",
    "정액핧아",
    "정자마셔",
    "정자먹어",
    "정자핧아",
    "젖같은",
    "젖까",
    "젖밥",
    "젖탱이",
    "조개넓은년",
    "조개따조",
    "조개마셔줘",
    "조개벌려조",
    "조개속물",
    "조개쑤셔줘",
    "조개핧아줘",
    "조까",
    "조또",
    "족같내",
    "족까",
    "족까내",
    "존나",
    "존나게",
    "존니",
    "졸라",
    "좀마니",
    "좀물",
    "좀쓰레기",
    "좁빠라라",
    "좃가튼뇬",
    "좃간년",
    "좃까",
    "좃까리",
    "좃깟네",
    "좃냄새",
    "좃넘",
    "좃대가리",
    "좃도",
    "좃또",
    "좃만아",
    "좃만이",
    "좃만한것",
    "좃만한쉐이",
    "좃물",
    "좃물냄새",
    "좃보지",
    "좃부랄",
    "좃빠구리",
    "좃빠네",
    "좃빠라라",
    "좃털",
    "좆같은놈",
    "좆같은새끼",
    "좆까",
    "좆까라",
    "좆나",
    "좆년",
    "좆도",
    "좆만아",
    "좆만한년",
    "좆만한놈",
    "좆만한새끼",
    "좆먹어",
    "좆물",
    "좆밥",
    "좆빨아",
    "좆새끼",
    "좆털",
    "좋만한것",
    "주글년",
    "주길년",
    "쥐랄",
    "지랄",
    "지랼",
    "지럴",
    "지뢀",
    "쪼까튼",
    "쪼다",
    "쪼다새끼",
    "찌랄",
    "찌질이",
    "창남",
    "창녀",
    "창녀버지",
    "창년",
    "처먹고",
    "처먹을",
    "쳐먹고",
    "쳐쑤셔박어",
    "촌씨브라리",
    "촌씨브랑이",
    "촌씨브랭이",
    "크리토리스",
    "큰보지",
    "클리토리스",
    "트랜스젠더",
    "페니스",
    "10새",
    "10새기",
    "10새리",
    "10세리",
    "10쉐이",
    "10쉑",
    "10스",
    "10쌔",
    "10쌔기",
    "10쎄",
    "10알",
    "10창",
    "10탱",
    "18",
    "18것",
    "18넘",
    "18노",
    "18뇬",
    "18럼",
    "18롬",
    "18새",
    "18색",
    "18세끼",
    "18세리",
    "18섹",
    "18쉑",
    "18스",
    "18아",
    "G스팟",
    "X끼",
    "ass",
    "bitch",
    "bogi",
    "boji",
    "bozi",
    "damm",
    "fuck",
    "g랄",
    "jaji",
    "jazi",
    "jot",
    "oral",
    "sex",
    "shit",
    "shutup",
    "sibal",
    "sipal",
    "si발",
    "ssiba",
    "suck",
    "tlqkf",
    "wtf",
    "zot",
    "z랄",
    "ㄱㅐ",
    "ㄲㅈ",
    "ㄲㅏ",
    "ㄲㅑ",
    "ㄲㅣ",
    "ㅁㅊ",
    "ㅂㅅ",
    "ㅄ",
    "ㅅㅂ",
    "ㅅㅂㄹㅁ",
    "ㅅㅍ",
    "ㅅㅐ",
    "ㅆㅍ",
    "ㅆ앙",
    "ㅈㄹ",
    "ㅍㅏ",
    "ㅗ",
    "凸",
    "간나",
    "갈보",
    "같은년",
    "같은뇬",
    "개가튼넘",
    "개같네",
    "개같은",
    "개구라",
    "개뇬",
    "개대중",
    "개독",
    "개돼중",
    "개랄",
    "개뻥",
    "개뿔",
    "개새기",
    "개새끼",
    "개새키",
    "개색기",
    "개색끼",
    "개색키",
    "개색히",
    "개섀끼",
    "개세끼",
    "개세이",
    "개소리",
    "개쇳기",
    "개수작",
    "개쉐",
    "개쉐리",
    "개쉐이",
    "개쉑",
    "개쉽",
    "개스끼",
    "개시키",
    "개십새기",
    "개십새끼",
    "개쌔끼",
    "개쐑",
    "개쑈",
    "개씹",
    "개아들",
    "개자슥",
    "개접",
    "개좌식",
    "개처럼",
    "개허접",
    "걔새",
    "걔수작",
    "걔시끼",
    "걔시키",
    "걔썌",
    "걸레",
    "게색기",
    "게색끼",
    "고추",
    "고츄",
    "곧츄",
    "곧휴",
    "곶츄",
    "곶휴",
    "광뇬",
    "구녕",
    "구라",
    "구멍",
    "그년",
    "그새끼",
    "까러",
    "깔어",
    "꺼져",
    "껃여",
    "껃져",
    "껒여",
    "꼬봉",
    "꼬우냐",
    "꼬추",
    "꼬츄",
    "꼳츄",
    "꼳휴",
    "꼴린다",
    "꼽냐",
    "꼽다",
    "꼽사리",
    "꽂추",
    "꽂츄",
    "냄비",
    "녜미",
    "놈현",
    "뇬",
    "눈까러",
    "눈깔",
    "눈깔어",
    "뉘미럴",
    "늬미",
    "늬미럴",
    "니귀미",
    "니미랄",
    "니미럴",
    "니미씹",
    "니아배",
    "니아베",
    "니어매",
    "니어메",
    "니엄마",
    "니어미",
    "닝기리",
    "닥쳐",
    "닥쵸",
    "닭쳐",
    "대가리",
    "대갈",
    "뎡신",
    "도라이",
    "돈놈",
    "돌아이",
    "돌은놈",
    "되질래",
    "뒈져",
    "뒈져라",
    "뒈진",
    "뒈진다",
    "뒈질",
    "뒤질래",
    "등신",
    "디져라",
    "디진다",
    "디질래",
    "딩시",
    "따식",
    "때놈",
    "또라이",
    "똘기",
    "똘아이",
    "똘추",
    "뙈놈",
    "뙤놈",
    "뙨넘",
    "뙨놈",
    "뚜쟁",
    "띠바",
    "띠발",
    "띠불",
    "랄지",
    "메친넘",
    "메친놈",
    "미췬",
    "미친",
    "미친스까이",
    "바랄년",
    "뱅마",
    "뱅신",
    "벼엉신",
    "병쉰",
    "병자",
    "부럴",
    "불할",
    "붕가",
    "붙어먹",
    "뷰웅",
    "븅",
    "빌어먹",
    "빌어먹을",
    "빙시",
    "빠가",
    "빠굴",
    "빠큐",
    "빡유",
    "빸유",
    "뻐큐",
    "뽀찌",
    "뽁큐",
    "삐리리",
    "사까아시",
    "사까아시이",
    "삿갓이",
    "상넘이",
    "상놈을",
    "상놈의",
    "상놈이",
    "새X",
    "새갸",
    "새새끼",
    "새키",
    "생쑈",
    "샫업",
    "샷업",
    "성노예",
    "세갸",
    "쇅끼",
    "쇡끼",
    "쇼하네",
    "쉐",
    "쉐기",
    "쉐리",
    "쉐에기",
    "쉐키",
    "쉑",
    "쉣",
    "쉨",
    "쉬박",
    "쉬밸",
    "쉬빡",
    "쉬뻘",
    "쉬탱",
    "쉬팍",
    "쉽세",
    "쉽알",
    "슈바",
    "슈발",
    "스패킹",
    "스팽",
    "시bal",
    "시궁창",
    "시끼",
    "시댕",
    "시뎅",
    "시랄",
    "시바",
    "시방",
    "시밬",
    "시부랄",
    "시부럴",
    "시부리",
    "시브랄",
    "시팍",
    "신발끈",
    "심발끈",
    "심탱",
    "십라",
    "십새끼",
    "십세",
    "십쉐이",
    "십스키",
    "십쌔",
    "싶알",
    "싸가지",
    "싹아지",
    "쌉년",
    "쌍뇬",
    "쌍쌍보지",
    "쌕",
    "쌩쑈",
    "쌰럽",
    "쌴년",
    "썅",
    "썡쇼",
    "써벌",
    "썩을년",
    "썩을놈",
    "쎄꺄",
    "쎄엑",
    "쎄엑스",
    "쎅쓰",
    "쑤시자",
    "쑤우시자",
    "쒸벌",
    "쒸뻘",
    "쒸팔",
    "쒸펄",
    "쓰바",
    "쓰박",
    "쓰발",
    "쓰벌",
    "쓰파",
    "쓰팔",
    "씁새",
    "씁얼",
    "씌파",
    "씨8",
    "씨가랭",
    "씨끼",
    "씨댕",
    "씨뎅",
    "씨바",
    "씨바랄",
    "씨박",
    "씨방",
    "씨뱅",
    "씨벨",
    "씨봉",
    "씨봉알",
    "씨부렁",
    "씨부리",
    "씨브랄",
    "씨빠",
    "씨뽀랄",
    "씨앙",
    "씨엑스",
    "씨파",
    "씨팍",
    "씨퐁",
    "씸년",
    "씸뇬",
    "씸새끼",
    "씹같",
    "씹뇬",
    "씹덕",
    "씹덕후",
    "씹새기",
    "씹새리",
    "씹쉐",
    "씹스키",
    "씹쌔",
    "씹이",
    "씹질",
    "씹퇭",
    "씹할",
    "씹헐",
    "아갈",
    "아갈빡",
    "아갈이",
    "아갈통",
    "아구창",
    "아구통",
    "아굴",
    "아닥",
    "아헤가오",
    "앰창",
    "얌마",
    "양넘",
    "양년",
    "양놈",
    "엠병",
    "엠창",
    "여물통",
    "염창",
    "엿같",
    "옘병",
    "옘빙",
    "오라질",
    "오라질년",
    "오입",
    "왜년",
    "왜놈",
    "욤병",
    "은년",
    "을년",
    "이새끼",
    "이새키",
    "이스끼",
    "이스키",
    "임마",
    "입싸",
    "자슥",
    "잡것",
    "잡넘",
    "저새끼",
    "접년",
    "정액",
    "젖꼭지",
    "젖꼮찌",
    "조까치",
    "조낸",
    "조랭",
    "조빠",
    "조쟁이",
    "조지냐",
    "조진다",
    "조질래",
    "조찐",
    "존만",
    "존만한",
    "졸래",
    "좁년",
    "좁밥",
    "좃",
    "좃만",
    "좃밥",
    "좃이",
    "좃찐",
    "좆",
    "좆같",
    "좆또",
    "좆만",
    "좆이",
    "좆찐",
    "좇같",
    "좇이",
    "좋같은",
    "좋만",
    "좌식",
    "주글",
    "주글래",
    "주데이",
    "주뎅",
    "주뎅이",
    "주둥아리",
    "주둥이",
    "주디",
    "주접",
    "주접떨",
    "죽고잡",
    "죽을래",
    "죽통",
    "쥐롤",
    "쥬디",
    "지X",
    "지ral",
    "지롤",
    "지미랄",
    "지스팟",
    "질싸",
    "짜식",
    "짜아식",
    "짜지",
    "짜찌",
    "쫍빱",
    "창놈",
    "쳐닥",
    "촌년",
    "촌놈",
    "캐년",
    "캐놈",
    "캐스끼",
    "캐스키",
    "캐시키",
    "탱구",
    "팔럼",
    "퍽큐",
    "헐보",
    "호구",
    "호로",
    "후라덜",
    "후라들",
    "후래자식",
    "후레자식",
    "후레",
    "후뢰",
    "후장",
    "새애액스",
    "세에엑스",
    "세애액스",
    "새에액스",
    "샥스",
    "쎽",
    "쎡",
    "쎾",
    "쏐",
    "쒝",
    "쒞",
    "챵년",
    "항문수셔",
    "항문쑤셔",
    "허덥",
    "허버리년",
    "허벌년",
    "허벌보지",
    "허벌자식",
    "허벌자지",
    "허접",
    "허젚",
    "허졉",
    "허좁",
    "헐렁보지",
    "혀로보지핧기",
    "호냥년",
    "호로새끼",
    "호로자슥",
    "호로자식",
    "호로짜식",
    "호루자슥",
    "호모",
    "호졉",
    "호좁",
    "후라덜넘",
    "후장꽂아",
    "후장뚫어",
    "흐접",
    "흐젚",
    "흐졉",
    "fuckyou",
    "nflavor",
    "penis",
    "pennis",
    "pussy",
    "개차반",
    "거유",
    "계집년",
    "고자",
    "근친",
    "노모",
    "때씹",
    "로리타",
    "망가",
    "몰카",
    "바바리맨",
    "변태",
    "스와핑",
    "씨발놈",
    "씹",
    "씹빨",
    "씹알",
    "암캐",
    "야동",
    "야사",
    "야애니",
    "에로",
    "유모",
    "은꼴",
    "자위",
    "종간나",
    "죽일년",
    "쥐좆",
    "직촬",
    "짱깨",
    "쪽바리",
    "포르노",
    "하드코어",
    "화냥년",
    "후레아들",
    "희쭈그리",
    "^l발",
    "ㅅㅣ발",
    "^ㅣ발",
    "^^ㅣ발",
    "^ㅣ빨",
    "^^ㅣ빨"
]; // 여기에 금지어 기입
client.on('messageCreate', async (message) => {
  if (!message.guild || message.author.bot) return;
  if (forbiddenWords.some(word => message.content.includes(word))) {
      const hasRole = message.member.roles.cache.some(r => r.id === '1146079297128370317' || r.id === '1098970312722366505');
      if (message.guild.ownerId === message.author.id || hasRole) return;
      await message.delete().catch(() => {});
      await message.channel.send(`${message.author}님, 금지어 사용으로 삭제되었습니다.`);
  }
});

// ==========================================
// 경고 로직
// ==========================================

const mongoose = require('mongoose');
const { EmbedBuilder, ApplicationCommandOptionType } = require('discord.js');

// MongoDB 연결
mongoose.connect(process.env.MONGODB_URI)
    .then(() => console.log('몽고DB 연결 성공'))
    .catch((err) => console.error('몽고DB 연결 실패:', err));

const warningSchema = new mongoose.Schema({
    guildId: String,
    userId: String,
    count: { type: Number, default: 0 }
});
const Warning = mongoose.model('Warning', warningSchema);

const guildSettingsSchema = new mongoose.Schema({
    guildId: { type: String, unique: true },
    maxWarnings: { type: Number, default: 5 }
});
const GuildSettings = mongoose.model('GuildSettings', guildSettingsSchema);

client.on('ready', async () => {
    const commands = [
        {
            name: '경고',
            description: '관리자가 직접 유저에게 경고를 부여합니다.',
            defaultMemberPermissions: PermissionFlagsBits.Administrator,
            options: [
                { name: '대상', description: '경고를 줄 대상자를 선택하세요.', type: ApplicationCommandOptionType.User, required: true },
                { name: '이유', description: '경고를 부여하는 명확한 이유를 적으세요.', type: ApplicationCommandOptionType.String, required: true },
                { name: '무슨말', description: '해당 유저가 채팅으로 무슨 말을 했는지 적으세요.', type: ApplicationCommandOptionType.String, required: true },
                { 
                    name: '조치사항', 
                    description: '유저에게 취할 조치 사항을 선택하세요.', 
                    type: ApplicationCommandOptionType.String, 
                    required: true,
                    choices: [
                        { name: '📢 구두 경고', value: '구두 경고' },
                        { name: '⏳ 1분 타임아웃', value: '1분 타임아웃' },
                        { name: '⏳ 5분 타임아웃', value: '5분 타임아웃' },
                        { name: '⏳ 10분 타임아웃', value: '10분 타임아웃' },
                        { name: '⏳ 30분 타임아웃', value: '30분 타임아웃' },
                        { name: '⏳ 1시간 타임아웃', value: '1시간 타임아웃' },
                        { name: '⏳ 2시간 타임아웃', value: '2시간 타임아웃' },
                        { name: '⏳ 4시간 타임아웃', value: '4시간 타임아웃' },
                        { name: '⏳ 8시간 타임아웃', value: '8시간 타임아웃' },
                        { name: '⏳ 12시간 타임아웃', value: '12시간 타임아웃' },
                        { name: '⏳ 18시간 타임아웃', value: '18시간 타임아웃' },
                        { name: '⏰ 하루 (24시간) 타임아웃', value: '하루 타임아웃' },
                        { name: '⏰ 이틀 (48시간) 타임아웃', value: '이틀 타임아웃' },
                        { name: '⏰ 사흘 (72시간) 타임아웃', value: '사흘 타임아웃' },
                        { name: '⏰ 나흘 (96시간) 타임아웃', value: '나흘 타임아웃' },
                        { name: '⏰ 일주일 (7일) 타임아웃', value: '7일 타임아웃' },
                        { name: '⏰ 이주일 (14일) 타임아웃', value: '14일 타임아웃' },
                        { name: '⏰ 삼주일 (21일) 타임아웃', value: '21일 타임아웃' },
                        { name: '⏰ 사주일 (28일 - 최대) 타임아웃', value: '28일 타임아웃' },
                        { name: '🚨 서버 추방 (킥)', value: '서버 추방 (킥)' },
                        { name: '🚫 서버 차단 (밴)', value: '서버 차단 (밴)' }
                    ]
                },
                { name: '누적경고수', description: '직접 지정할 누적 경고 수 (비워두면 자동 +1)', type: ApplicationCommandOptionType.Integer, required: false }
            ]
        },
        {
            name: '경고차감',
            description: '관리자가 유저의 누적 경고 수를 차감합니다.',
            defaultMemberPermissions: PermissionFlagsBits.Administrator,
            options: [
                { name: '대상', description: '경고를 차감할 대상 유저를 선택하세요.', type: ApplicationCommandOptionType.User, required: true },
                { name: '차감수', description: '차감할 경고 개수를 적으세요.', type: ApplicationCommandOptionType.Integer, required: true },
                { name: '사유', description: '경고를 차감해주는 명확한 사유를 적으세요.', type: ApplicationCommandOptionType.String, required: false }
            ]
        },
        {
            name: '경고한도',
            description: '서버의 최대 누적 경고 제한 수치를 확인하거나 수정합니다.',
            defaultMemberPermissions: PermissionFlagsBits.Administrator,
            options: [
                { name: '설정값', description: '변경할 경고 한도 숫자를 입력하세요. (비워두면 현재 한도 조회)', type: ApplicationCommandOptionType.Integer, required: false }
            ]
        }
    ];

    const rest = new REST({ version: '10' }).setToken(process.env.TOKEN);
    try {
        client.guilds.cache.forEach(async (guild) => {
            await rest.put(Routes.applicationGuildCommands(client.user.id, guild.id), { body: commands });
        });
    } catch (error) {
        console.error('경고 명령어 등록 중 에러 발생:', error);
    }
});

client.on('interactionCreate', async (interaction) => {
    if (!interaction.isChatInputCommand()) return;
    const { commandName } = interaction;

    if (commandName === '경고') {
        const isOwner = interaction.guild.ownerId === interaction.user.id;
        const hasPermissionRole = interaction.member.roles.cache.some(role => role.id === '1146079297128370317' || role.id === '1098970312722366505');
        if (!isOwner && !hasPermissionRole) return await interaction.reply({ content: '❌ 권한이 없습니다.', ephemeral: true });

        const targetUser = interaction.options.getUser('대상');
        const targetMember = interaction.options.getMember('대상'); 
        const reason = interaction.options.getString('이유');
        const whatTheySaid = interaction.options.getString('무슨말');
        const actionTaken = interaction.options.getString('조치사항');
        const customCount = interaction.options.getInteger('누적경고수');

        let finalCount;
        if (customCount !== null) {
            await Warning.findOneAndUpdate({ guildId: interaction.guild.id, userId: targetUser.id }, { count: customCount }, { upsert: true });
            finalCount = customCount;
        } else {
            const userData = await Warning.findOneAndUpdate({ guildId: interaction.guild.id, userId: targetUser.id }, { $inc: { count: 1 } }, { upsert: true, new: true });
            finalCount = userData ? userData.count : 1;
        }

        let duration = 0;
        if (actionTaken.includes('분')) duration = parseInt(actionTaken) * 60 * 1000;
        else if (actionTaken.includes('시간')) duration = parseInt(actionTaken) * 60 * 60 * 1000;
        else if (actionTaken === '하루 타임아웃') duration = 24 * 60 * 60 * 1000;
        else if (actionTaken === '이틀 타임아웃') duration = 48 * 60 * 60 * 1000;
        else if (actionTaken === '사흘 타임아웃') duration = 72 * 60 * 60 * 1000;
        else if (actionTaken === '나흘 타임아웃') duration = 96 * 60 * 60 * 1000;
        else if (actionTaken.includes('일 타임아웃')) duration = parseInt(actionTaken) * 24 * 60 * 60 * 1000;

        let realActionText = `**${actionTaken}**`;
        if (targetMember) {
            if (duration > 0 && targetMember.moderatable) await targetMember.timeout(duration, `관리자 수동 제재: ${reason}`).catch(console.error);
            else if (actionTaken === '서버 추방 (킥)' && targetMember.kickable) { await targetMember.kick(`관리자 수동 제재: ${reason}`).catch(console.error); realActionText = '🔥 **서버 추방 (킥) 완료**'; }
            else if (actionTaken === '서버 차단 (밴)' && targetMember.bannable) { await targetMember.ban({ reason: `관리자 수동 제재: ${reason}` }).catch(console.error); realActionText = '🚫 **서버 영구 차단 (밴) 완료**'; }
        }

        const warnChannel = interaction.guild.channels.cache.find(ch => ch.name === '경고');
        const manualEmbed = new EmbedBuilder()
            .setTitle('⚠️ [수동 제재] 관리자 경고')
            .setColor(0xFFCC00)
            .addFields(
                { name: '👤 시행자', value: `<@${interaction.user.id}>`, inline: true },
                { name: '🎯 대상자', value: `<@${targetUser.id}>`, inline: true },
                { name: '📊 누적 경고 수', value: `**${finalCount}회**`, inline: true },
                { name: '⏳ 조치 사항', value: realActionText, inline: true },
                { name: '📝 경고 이유', value: reason },
                { name: '💬 무슨 말을 했는지', value: `\`\`\`${whatTheySaid}\`\`\`` }
            ).setTimestamp();

        if (warnChannel) await warnChannel.send({ embeds: [manualEmbed] }).catch(() => {});
        await interaction.reply({ content: `🚨 <@${targetUser.id}>님에게 수동 경고 조치를 완료했습니다.`, embeds: [manualEmbed] });
    }

    if (commandName === '경고차감') {
        const isOwner = interaction.guild.ownerId === interaction.user.id;
        const hasPermissionRole = interaction.member.roles.cache.some(role => role.id === '1146079297128370317' || role.id === '1098970312722366505');
        if (!isOwner && !hasPermissionRole) return await interaction.reply({ content: '❌ 권한이 없습니다.', ephemeral: true });

        const targetUser = interaction.options.getUser('대상');
        const reduceAmount = interaction.options.getInteger('차감수');
        const reason = interaction.options.getString('사유');
        let userData = await Warning.findOne({ guildId: interaction.guild.id, userId: targetUser.id });
        let beforeCount = userData ? userData.count : 0;
        let afterCount = Math.max(0, beforeCount - reduceAmount);

        userData = await Warning.findOneAndUpdate({ guildId: interaction.guild.id, userId: targetUser.id }, { count: afterCount }, { upsert: true, new: true });
        const warnChannel = interaction.guild.channels.cache.find(ch => ch.name === '경고');

        const deductEmbed = new EmbedBuilder()
            .setTitle('🟢 [경고 차감] 관리자 면제 조치')
            .setColor(0x00FF00)
            .addFields(
                { name: '👤 시행자', value: `<@${interaction.user.id}>`, inline: true },
                { name: '🎯 대상자', value: `<@${targetUser.id}>`, inline: true },
                { name: '📊 경고 변동 사항', value: `**${beforeCount}회 ➡️ ${userData.count}회** (\`-${reduceAmount}\`)`, inline: true }
            ).setTimestamp();
        
        if (reason) deductEmbed.addFields({ name: '📝 차감 사유', value: reason });
        if (warnChannel) await warnChannel.send({ embeds: [deductEmbed] }).catch(() => {});
        await interaction.reply({ content: `✅ <@${targetUser.id}>님의 경고를 차감하였습니다.`, embeds: [deductEmbed] });
    }

    if (commandName === '경고한도') {
        const isOwner = interaction.guild.ownerId === interaction.user.id;
        const hasPermissionRole = interaction.member.roles.cache.some(role => role.id === '1146079297128370317' || role.id === '1098970312722366505');
        if (!isOwner && !hasPermissionRole) return await interaction.reply({ content: '❌ 권한이 없습니다.', ephemeral: true });

        const newLimit = interaction.options.getInteger('설정값');
        if (newLimit === null) {
            const settings = await GuildSettings.findOne({ guildId: interaction.guild.id });
            return await interaction.reply({ embeds: [new EmbedBuilder().setTitle('⚙️ 서버 경고 한도 정보').setDescription(`현재 한도: **${settings ? settings.maxWarnings : 5}회**`)] });
        }
        await GuildSettings.findOneAndUpdate({ guildId: interaction.guild.id }, { maxWarnings: newLimit }, { upsert: true });
        await interaction.reply({ content: `✅ 경고 한도가 **${newLimit}회**로 변경되었습니다.` });
    }
});
